// <auto-generated />
using System;
using Auth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    partial class AuthDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Entities.Organization", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ParentId")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 659, DateTimeKind.Utc).AddTicks(8750),
                            Status = (byte)1,
                            Title = "Auth.Service"
                        },
                        new
                        {
                            Id = new byte[] { 1, 145, 106, 139, 32, 123, 205, 111, 137, 86, 72, 123, 76, 224, 81, 14 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 659, DateTimeKind.Utc).AddTicks(8770),
                            ParentId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            Status = (byte)1,
                            Title = "Accounting.Service"
                        },
                        new
                        {
                            Id = new byte[] { 1, 145, 106, 139, 183, 77, 220, 76, 77, 22, 99, 90, 112, 204, 45, 8 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 659, DateTimeKind.Utc).AddTicks(8770),
                            ParentId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            Status = (byte)1,
                            Title = "RedSense.Service"
                        },
                        new
                        {
                            Id = new byte[] { 1, 145, 106, 53, 249, 102, 223, 110, 72, 121, 238, 195, 21, 7, 23, 232 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 659, DateTimeKind.Utc).AddTicks(8810),
                            ParentId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            Status = (byte)1,
                            Title = "RedGuard.Update.Service"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.Permission", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<byte[]>("RoleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 145, 194, 17, 51, 104, 213, 0, 96, 96, 6, 174, 40, 102, 47, 34 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 701, DateTimeKind.Utc).AddTicks(8930),
                            ResourceId = new byte[] { 1, 145, 194, 19, 100, 213, 195, 167, 224, 76, 129, 159, 122, 140, 74, 9 },
                            RoleId = new byte[] { 1, 145, 106, 169, 155, 50, 131, 103, 80, 86, 64, 7, 186, 122, 115, 182 }
                        },
                        new
                        {
                            Id = new byte[] { 1, 145, 194, 48, 229, 40, 27, 168, 73, 211, 5, 201, 74, 251, 113, 198 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 701, DateTimeKind.Utc).AddTicks(8930),
                            ResourceId = new byte[] { 1, 145, 194, 46, 218, 213, 189, 253, 172, 150, 128, 62, 74, 166, 112, 183 },
                            RoleId = new byte[] { 1, 145, 106, 169, 155, 50, 131, 103, 80, 86, 64, 7, 186, 122, 115, 182 }
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.Resource", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("GroupId")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 145, 194, 19, 100, 213, 195, 167, 224, 76, 129, 159, 122, 140, 74, 9 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 701, DateTimeKind.Utc).AddTicks(7800),
                            GroupId = new byte[] { 1, 145, 194, 42, 195, 53, 198, 72, 83, 119, 87, 191, 13, 30, 74, 191 },
                            OrganizationId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            Title = "Auth.User.Create",
                            Url = "/user"
                        },
                        new
                        {
                            Id = new byte[] { 1, 145, 194, 46, 218, 213, 189, 253, 172, 150, 128, 62, 74, 166, 112, 183 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 701, DateTimeKind.Utc).AddTicks(7800),
                            GroupId = new byte[] { 1, 145, 194, 42, 195, 53, 198, 72, 83, 119, 87, 191, 13, 30, 74, 191 },
                            OrganizationId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            Title = "Auth.User.ListByFilters",
                            Url = "/user/list/filter"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.ResourceGroup", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("varbinary(200)");

                    b.Property<byte[]>("ParentId")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParentId");

                    b.ToTable("ResourceGroups");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 145, 194, 42, 195, 53, 198, 72, 83, 119, 87, 191, 13, 30, 74, 191 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 701, DateTimeKind.Utc).AddTicks(6370),
                            Order = 1,
                            OrganizationId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            Title = "Auth.Users"
                        },
                        new
                        {
                            Id = new byte[] { 1, 145, 194, 45, 99, 78, 65, 54, 202, 171, 255, 86, 230, 97, 209, 207 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 701, DateTimeKind.Utc).AddTicks(6370),
                            Order = 2,
                            OrganizationId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            Title = "Auth.Organizations"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.Role", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 145, 106, 169, 155, 50, 131, 103, 80, 86, 64, 7, 186, 122, 115, 182 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 659, DateTimeKind.Utc).AddTicks(9690),
                            OrganizationId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            Status = (byte)1,
                            Title = "Admin.Auth.Service"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<DateTime?>("AccountLockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEmailValid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneValid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 145, 110, 104, 183, 60, 4, 137, 1, 231, 28, 132, 171, 255, 73, 237 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 660, DateTimeKind.Utc).AddTicks(220),
                            FailedLoginAttempts = 0,
                            Family = "Auth.Service",
                            IsEmailValid = false,
                            IsPhoneValid = false,
                            Name = "Admin",
                            Password = "icoMg8j2l99NC7JaDWHofIL6jJsut20+7kWSohXr6vKU1niIvwchn47i44Sr72bP",
                            Status = (byte)1,
                            Username = "AdminAuthService1"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.UserOrganization", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<byte[]>("RoleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varbinary(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOrganizations");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 145, 110, 124, 211, 13, 172, 121, 123, 233, 248, 119, 101, 211, 216, 0 },
                            CreateAt = new DateTime(2024, 9, 5, 12, 45, 38, 701, DateTimeKind.Utc).AddTicks(5300),
                            OrganizationId = new byte[] { 1, 145, 106, 136, 242, 8, 4, 73, 225, 232, 220, 197, 197, 104, 46, 232 },
                            RoleId = new byte[] { 1, 145, 106, 169, 155, 50, 131, 103, 80, 86, 64, 7, 186, 122, 115, 182 },
                            UserId = new byte[] { 1, 145, 110, 104, 183, 60, 4, 137, 1, 231, 28, 132, 171, 255, 73, 237 }
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.Organization", b =>
                {
                    b.HasOne("Auth.Domain.Entities.Organization", "Parent")
                        .WithMany("Chides")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Permission", b =>
                {
                    b.HasOne("Auth.Domain.Entities.Resource", "Resource")
                        .WithMany("Permissions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Resource", b =>
                {
                    b.HasOne("Auth.Domain.Entities.ResourceGroup", "Group")
                        .WithMany("Resources")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Auth.Domain.Entities.Organization", "Organization")
                        .WithMany("Resources")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Auth.Domain.Entities.ResourceGroup", b =>
                {
                    b.HasOne("Auth.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Entities.ResourceGroup", "Parent")
                        .WithMany("Chields")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organization");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Role", b =>
                {
                    b.HasOne("Auth.Domain.Entities.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Auth.Domain.Entities.UserOrganization", b =>
                {
                    b.HasOne("Auth.Domain.Entities.Organization", "Organization")
                        .WithMany("UserOrganizations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Entities.Role", "Role")
                        .WithMany("UserOrganizations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Entities.User", "User")
                        .WithMany("UserOrganizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Chides");

                    b.Navigation("Resources");

                    b.Navigation("Roles");

                    b.Navigation("UserOrganizations");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Resource", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Auth.Domain.Entities.ResourceGroup", b =>
                {
                    b.Navigation("Chields");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserOrganizations");
                });

            modelBuilder.Entity("Auth.Domain.Entities.User", b =>
                {
                    b.Navigation("UserOrganizations");
                });
#pragma warning restore 612, 618
        }
    }
}
